env:
  - GO111MODULE=on
  - CGO_ENABLED=0

builds:
  - binary: doggo
    id: cli
    goos:
      - windows
      - darwin
      - linux
    goarch:
      - amd64
      - arm64
    goarm:
      - 6
      - 7
    ldflags:
      - -s -w -X "main.buildVersion={{ .Tag }} ({{ .ShortCommit }} {{ .Date }})"
    dir: ./cmd/doggo/

  - binary: doggo-api.bin
    id: api
    goos:
      - windows
      - darwin
      - linux
    goarch:
      - amd64
      - arm64
    goarm:
      - 6
      - 7
    ldflags:
      - -s -w -X "main.buildVersion={{ .Tag }} ({{ .ShortCommit }} {{ .Date }})"
    dir: ./cmd/api/

archives:
  - format: tar.gz
    files:
      - README.md
      - LICENSE
      - completions/

dockers:
  - image_templates:
      - "ghcr.io/mr-karan/doggo:{{ .Tag }}"
      - "ghcr.io/mr-karan/doggo:latest"
    id: doggo
    # IDs to filter the binaries/packages.
    ids:
      - cli
    dockerfile: Dockerfile-cli
    build_flag_templates:
      - "--build-arg"
      - "ARCH=amd64"
  - image_templates:
      - "ghcr.io/mr-karan/doggo:{{ .Tag }}-arm64v8"
      - "ghcr.io/mr-karan/doggo:latest-arm64v8"
    id: doggo-arm
    # IDs to filter the binaries/packages.
    ids:
      - cli
    goarch: arm64
    dockerfile: Dockerfile-cli
    build_flag_templates:
      - "--build-arg"
      - "ARCH=arm64v8"

  - image_templates:
      - "ghcr.io/mr-karan/doggo:api{{ .Tag }}"
      - "ghcr.io/mr-karan/doggo:api:latest"
    id: doggo-api
    ids:
      - api
    dockerfile: Dockerfile-api
    build_flag_templates:
      - "--build-arg"
      - "ARCH=amd64"
    extra_files:
      - config-api-sample.toml
  - image_templates:
      - "ghcr.io/mr-karan/doggo-api:{{ .Tag }}-arm64v8"
      - "ghcr.io/mr-karan/doggo-api:latest-arm64v8"
    id: doggo-api-arm
    ids:
      - api
    goarch: arm64
    dockerfile: Dockerfile-api
    build_flag_templates:
      - "--build-arg"
      - "ARCH=arm64v8"
    extra_files:
      - config-api-sample.toml
