env:
  - GO111MODULE=on
  - CGO_ENABLED=0

builds:
  - binary: doggo
    goos:
      - windows
      - darwin
      - linux
    goarch:
      - amd64
      - arm64
    goarm:
      - 6
      - 7
    ldflags:
      - -s -w -X "main.buildVersion={{ .Tag }} ({{ .ShortCommit }} {{ .Date }})"
    dir: ./cmd/

archives:
  - format: tar.gz
    files:
      - README.md
      - LICENSE

snapcrafts:
  - name_template: "{{ .ProjectName }}_{{ .Arch }}{{ if .Arm }}v{{ .Arm }}{{ end }}"
    summary: Command-line DNS client.
    description: |
      doggo is a command-line DNS client written in Go. It supports protocols like DoH, DoT and output formats like JSON.
    grade: stable
    confinement: strict
    publish: true

dockers:
- image_templates:
  - "ghcr.io/mr-karan/doggo:{{ .Tag }}"
  - "ghcr.io/mr-karan/doggo:latest"
  binaries:
  - doggo
  dockerfile: Dockerfile
  build_flag_templates:
  - "--build-arg"
  - "ARCH=amd64"
- image_templates:
  - "ghcr.io/mr-karan/doggo:{{ .Tag }}-arm64v8"
  - "ghcr.io/mr-karan/doggo:latest-arm64v8"
  binaries:
  - doggo
  goarch: arm64
  dockerfile: Dockerfile
  build_flag_templates:
  - "--build-arg"
  - "ARCH=arm64v8"
